# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/new/display640x480.vh}}
set_property file_type "Verilog Header" [get_files {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/new/display640x480.vh}}]
read_mem {
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/new/imem_screentest_nopause.mem}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/new/dmem_screentest.mem}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/new/smem_screentest.mem}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/new/bmem_screentest.mem}
}
read_verilog -library xil_defaultlib -sv {
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/ALU.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/sources/accelerometer.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/adder.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/addsub.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/new/clockdivider_Nexys4.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/comparator.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/sources_1/new/controller.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/sources_1/imports/new/datapath.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/display8digit.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/fulladder.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/hexto7seg.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/keyboard.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/logical.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/new/memIO.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/mips.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/montek_sound_Nexys4.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/ram_module.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/new/ram_module_2port.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/sources_1/new/register_file.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/rom_module.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/shifter.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/vgadisplaydriver.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/vgatimer.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/new/xycounter.sv}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/new/top.sv}
}
read_vhdl -library xil_defaultlib {
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/sources/ADXL362Ctrl.vhd}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/sources/AccelArithmetics.vhd}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/sources/AccelerometerCtl.vhd}
  {C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/sources_1/imports/sources/SPI_If.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/new/clock.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/new/clock.xdc}}]

read_xdc {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/new/reset.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/new/reset.xdc}}]

read_xdc {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/new/vga.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/new/vga.xdc}}]

read_xdc {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/imports/new/accelerometer.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/imports/new/accelerometer.xdc}}]

read_xdc {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/imports/new/ledLights.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/imports/new/ledLights.xdc}}]

read_xdc {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/imports/new/segdisplay.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/imports/new/segdisplay.xdc}}]

read_xdc {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/imports/new/sound.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/imports/new/sound.xdc}}]

read_xdc {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/imports/new/Nexis4.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/final_project/final_project.srcs/constrs_1/imports/new/Nexis4.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
