webtalk_init -webtalk_dir C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/lab2a/lab2a.sim/sim_1/behav/xsim/xsim.dir/fulladder_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 17 13:54:41 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3d9e8bf3-1e19-4e52-80e3-a2fb876e31d8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d3eea531d3b94b81a6d0ef38bddc3e65" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "22 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5536_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3072964328 -regid "" -xml C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/lab2a/lab2a.sim/sim_1/behav/xsim/xsim.dir/fulladder_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/lab2a/lab2a.sim/sim_1/behav/xsim/xsim.dir/fulladder_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/lab2a/lab2a.sim/sim_1/behav/xsim/xsim.dir/fulladder_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
