@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Jan 24 13:48:00 -0500 2020
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim Lab2b_Part4_32bit_test_behav -key {Behavioral:sim_8:Functional:Lab2b_Part4_32bit_test} -tclbatch Lab2b_Part4_32bit_test.tcl -view C:/Users/lkeilly/Desktop/UNC stuff/Spring2020/COMP541/Labs/projects/lab2a/Lab2b_Part4_32bit_test_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
